# Generated by Django 5.1.4 on 2025-01-12 13:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_vacancies',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('count', models.CharField(max_length=10, verbose_name='Количество вакансий')),
            ],
            options={
                'verbose_name': 'Динамика количества вакансий по годам',
                'verbose_name_plural': 'Динамику количества вакансий по годам',
            },
        ),
        migrations.AlterModelOptions(
            name='salary_years',
            options={'verbose_name': 'Динамику уровня зарплат по годам', 'verbose_name_plural': 'Динамика уровня зарплат по годам'},
        ),
        migrations.AlterField(
            model_name='salary_years',
            name='average_salary',
            field=models.CharField(max_length=10, verbose_name='Средняя зарплата'),
        ),
    ]
