# Generated by Django 5.1.4 on 2025-01-12 15:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_number_vacancies_alter_salary_years_options_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Год')),
                ('average_salary', models.CharField(max_length=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам',
                'verbose_name_plural': 'Уровень зарплат по городам',
            },
        ),
        migrations.AlterModelOptions(
            name='number_vacancies',
            options={'verbose_name': 'Динамику количества вакансий по годам', 'verbose_name_plural': 'Динамика количества вакансий по годам'},
        ),
    ]
