# Generated by Django 5.1.4 on 2025-01-12 17:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0003_salary_city_alter_number_vacancies_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vacancy_rate_city',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('rate_vacancy', models.CharField(max_length=10, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам',
                'verbose_name_plural': 'Доля вакансий по городам',
            },
        ),
        migrations.AlterField(
            model_name='salary_city',
            name='city',
            field=models.CharField(max_length=20, verbose_name='Город'),
        ),
    ]
