# Generated by Django 5.1.4 on 2025-01-12 18:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0004_vacancy_rate_city_alter_salary_city_city'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20, verbose_name='Навык')),
                ('count', models.CharField(max_length=10, verbose_name='Количество')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков',
                'verbose_name_plural': 'ТОП-20 навыков',
            },
        ),
    ]
