# Generated by Django 5.1.4 on 2025-01-13 10:36

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0005_skills'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_years_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('average_salary', models.CharField(max_length=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Динамику уровня зарплат по годам для 1С разработчика',
                'verbose_name_plural': 'Динамика уровня зарплат по годам для 1С разработчика',
            },
        ),
        migrations.CreateModel(
            name='Salary_years_developer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img1', models.ImageField(blank=True, null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка уровня зарплат по годам для 1С разработчика',
            },
        ),
        migrations.AlterField(
            model_name='skills',
            name='count',
            field=models.CharField(max_length=10, verbose_name='Количество упоминаний'),
        ),
    ]
