# Generated by Django 5.1.4 on 2025-01-14 13:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0006_salary_years_developer_salary_years_developer_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Number_vacancies_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('year', models.CharField(max_length=4, verbose_name='Год')),
                ('count', models.CharField(max_length=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Динамику количества вакансий по годам для 1С разработчика',
                'verbose_name_plural': 'Динамика количества вакансий по годам для 1С разработчика',
            },
        ),
        migrations.CreateModel(
            name='Number_vacancies_developer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img2', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка динамики количества вакансий по годам для 1С разработчика',
            },
        ),
        migrations.AlterField(
            model_name='salary_years_developer_img',
            name='img1',
            field=models.ImageField(null=True, upload_to='images/'),
        ),
    ]
