# Generated by Django 5.1.4 on 2025-01-14 13:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0007_number_vacancies_developer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Salary_city_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('average_salary', models.CharField(max_length=10, verbose_name='Средняя зарплата')),
            ],
            options={
                'verbose_name': 'Уровень зарплат по городам для 1С разработчика',
                'verbose_name_plural': 'Уровень зарплат по городам для 1С разработчика',
            },
        ),
        migrations.CreateModel(
            name='Salary_city_developer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img3', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка уровня зарплат по городам для 1С разработчика',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_rate_city_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('city', models.CharField(max_length=20, verbose_name='Город')),
                ('rate_vacancy', models.CharField(max_length=10, verbose_name='Доля вакансий')),
            ],
            options={
                'verbose_name': 'Доля вакансий по городам для 1С разработчика',
                'verbose_name_plural': 'Доля вакансий по городам для 1С разработчика',
            },
        ),
        migrations.CreateModel(
            name='Vacancy_rate_city_developer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img4', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка доли вакансий по городам для 1С разработчика',
            },
        ),
        migrations.AlterField(
            model_name='number_vacancies_developer',
            name='count',
            field=models.CharField(max_length=10, verbose_name='Количество вакансий'),
        ),
    ]
