# Generated by Django 5.1.4 on 2025-01-14 15:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0008_salary_city_developer_salary_city_developer_img_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='Skills_developer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('skill', models.CharField(max_length=20, verbose_name='Навык')),
                ('count', models.CharField(max_length=10, verbose_name='Количество упоминаний')),
            ],
            options={
                'verbose_name': 'ТОП-20 навыков',
                'verbose_name_plural': 'ТОП-20 навыков',
            },
        ),
        migrations.CreateModel(
            name='Skills_developer_img',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('img5', models.ImageField(null=True, upload_to='images/')),
            ],
            options={
                'verbose_name': 'Картинка топа навыков для 1С разработчика',
            },
        ),
    ]
